### PR TITLE
Rename Option to Maybe

### PR DESCRIPTION
**Pull request by hojberg**
* Option -> Maybe
* None -> Nothing
* Some -> Just

Let me know if actual implementation was meant to change as well, as far as I understand it the implementation would be the same?

---
This change is [Reviewable](https://reviewable.io/reviews/fantasyland/fantasy-maybes/9)

### CODE REVIEW

**Comment by davidchambers** [comment]
I'd like to see something more drastic. I'd like to completely replace the existing implementation with the [Sanctuary implementation][1]. Initially I'd planned to create a new repository for this purpose (see sanctuary-js/sanctuary-maybe#1) but @SimonRichardson and I are keen to reduce the number of implementations of each FL-compatible data type and believe the canonical implementations should live in the @fantasyland account.


[1]: https://github.com/sanctuary-js/sanctuary/blob/62877fce6fbab9dbcdfeb8250ffc776b569578e6/index.js#L859-L1188

**Comment by SimonRichardson** [comment]
I'd still like to rely on daggy if possible though, but that's my only requirement.

**Comment by davidchambers** [comment]
> I'd still like to rely on daggy

Is this because you consider it important to provide a `cata` method, or for some other reason?

**Comment by SimonRichardson** [comment]
Yeah, it does the lifting of `cata` for free, which I've found to be extremely useful.

**Comment by safareli** [comment]
Also on note, I will create PR for daggy based on my [union.js](https://github.com/safareli/free/blob/par/src/union.js) it has `cata` `toString` and `tag` for "free"  uses no constructor Functions, doesn't support `instanceof` and I belive it's a bit efficient.

**Comment by hojberg** [comment]
Now that repo is renamed, is this PR good to go or is there any feedback I need to address

**Comment by SimonRichardson** [comment]
https://github.com/puffnfresh/daggy/issues/7

**Comment by nikolal** [comment]
When will this be merged?

**Comment by joshburgess** [comment]
Any updates on this? I just stumbled on all of these discussions/issues/PRs while trying to find a Maybe package to use. It looks looks like it's been sitting for quite a while now.

**Comment by gabejohnson** [comment]
@davidchambers @safareli @SimonRichardson is anyone going to merge this? Someone on fpchat was asking about it.

**Comment by amsross** [comment]
image

**Comment by radmen** [comment]
Folks, just wanted to say that I'd love to see this PR merged :)

I've just stumbled on this package yesterday and decided to not use it due naming (I know, lame of me) :/

**Comment by joshburgess** [comment]
+1 Can we get this merged? Do you need extra maintainers to help out?

**Comment by rgeraldporter** [comment]
@davidchambers @SimonRichardson @safareli any word on merge? need a maintainer?

**Comment by davidchambers** [comment]
> need a maintainer?

This project should be archived as soon as sanctuary-js/sanctuary-maybe#3 is merged and released. @fantasyland projects—aside from the specification itself—tend not to be updated, and even if this were not the case, maintaining two equivalent projects would not be a good use of our limited time.

**Comment by davidchambers** [comment]
[sanctuary-maybe][1] has been released, so I'll close this pull request and archive this project. Thank you nonetheless for your contribution, @hojberg. I hope sanctuary-maybe satisfies your requirements.


[1]: https://github.com/sanctuary-js/sanctuary-maybe

**Pull request closed without merging**
